services:
  - type: web
    name: lightweight-data-analyst
    env: python
    pythonVersion: "3.10.14"  # FORCE older Python version
    buildCommand: |
      echo "==> Python version check"
      python --version
      python -c "import sys; print(f'Python: {sys.version}')"
      echo "==> Upgrading build tools FIRST"
      python -m pip install --upgrade pip==23.3.2
      python -m pip install --upgrade setuptools==69.0.3 wheel==0.42.0
      echo "==> Installing dependencies with pre-built wheels only"
      pip install --only-binary=all --no-compile -r requirements.txt
      echo "==> Verifying installation"
      python -c "import flask; print('Flask OK')"
      python -c "import pandas; print('Pandas OK')" 
      python -c "import plotly; print('Plotly OK')"
      echo "==> Build completed successfully"
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 2 app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE  
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"