services:
  - type: web
    name: data-analyst-agent-sriharsan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 180 --workers 2 app:app
    pythonVersion: 3.10
